module.exports = {
    provinceArray: [ {
        regid: "2",
        regname: "北京市",
    }, {
        regid: "3",
        regname: "安徽省",
    }, {
        regid: "4",
        regname: "福建省",
    }, {
        regid: "5",
        regname: "甘肃省",
    }, {
        regid: "6",
        regname: "广东省",
    }, {
        regid: "7",
        regname: "广西省",
    }, {
        regid: "8",
        regname: "贵州省",
    }, {
        regid: "9",
        regname: "海南省",
    }, {
        regid: "10",
        regname: "河北省",
    }, {
        regid: "11",
        regname: "河南省",
    }, {
        regid: "12",
        regname: "黑龙江自治区",
    }, {
        regid: "13",
        regname: "湖北省",
    }, {
        regid: "14",
        regname: "湖南省",
    }, {
        regid: "15",
        regname: "吉林省",
    }, {
        regid: "16",
        regname: "江苏省",
    }, {
        regid: "17",
        regname: "江西省",
    }, {
        regid: "18",
        regname: "辽宁省",
    }, {
        regid: "19",
        regname: "内蒙古自治区",
    }, {
        regid: "20",
        regname: "宁夏回族自治区",
    }, {
        regid: "21",
        regname: "青海省",
    }, {
        regid: "22",
        regname: "山东省",
    }, {
        regid: "23",
        regname: "山西省",
    }, {
        regid: "24",
        regname: "陕西省",
    }, {
        regid: "25",
        regname: "上海市",
    }, {
        regid: "26",
        regname: "四川省",
    }, {
        regid: "27",
        regname: "天津省",
    }, {
        regid: "28",
        regname: "西藏自治区",
    }, {
        regid: "29",
        regname: "新疆维吾尔自治区",
    }, {
        regid: "30",
        regname: "云南省",
    }, {
        regid: "31",
        regname: "浙江省",
    }, {
        regid: "32",
        regname: "重庆省",
    }, {
        regid: "33",
        regname: "香港",
    }, {
        regid: "34",
        regname: "澳门",
    }, {
        regid: "35",
        regname: "台湾",
    } ],
    cityArray: [ {
        regid: "36",
        parid: "3",
        regname: "安庆市",
    }, {
        regid: "37",
        parid: "3",
        regname: "蚌埠市",
    }, {
        regid: "38",
        parid: "3",
        regname: "巢湖市",
    }, {
        regid: "39",
        parid: "3",
        regname: "池州市",
    }, {
        regid: "40",
        parid: "3",
        regname: "滁州市",
    }, {
        regid: "41",
        parid: "3",
        regname: "阜阳市",
    }, {
        regid: "42",
        parid: "3",
        regname: "淮北市",
    }, {
        regid: "43",
        parid: "3",
        regname: "淮南市",
    }, {
        regid: "44",
        parid: "3",
        regname: "黄山市",
    }, {
        regid: "45",
        parid: "3",
        regname: "六安市",
    }, {
        regid: "46",
        parid: "3",
        regname: "马鞍山市",
    }, {
        regid: "47",
        parid: "3",
        regname: "宿州市",
    }, {
        regid: "48",
        parid: "3",
        regname: "铜陵市",
    }, {
        regid: "49",
        parid: "3",
        regname: "芜湖市",
    }, {
        regid: "50",
        parid: "3",
        regname: "宣城市",
    }, {
        regid: "51",
        parid: "3",
        regname: "亳州市",
    }, {
        regid: "52",
        parid: "2",
        regname: "北京市",
    }, {
        regid: "53",
        parid: "4",
        regname: "福州市",
    }, {
        regid: "54",
        parid: "4",
        regname: "龙岩市",
    }, {
        regid: "55",
        parid: "4",
        regname: "南平市",
    }, {
        regid: "56",
        parid: "4",
        regname: "宁德市",
    }, {
        regid: "57",
        parid: "4",
        regname: "莆田市",
    }, {
        regid: "58",
        parid: "4",
        regname: "泉州市",
    }, {
        regid: "59",
        parid: "4",
        regname: "三明市",
    }, {
        regid: "60",
        parid: "4",
        regname: "厦门市",
    }, {
        regid: "61",
        parid: "4",
        regname: "漳州市",
    }, {
        regid: "62",
        parid: "5",
        regname: "兰州市",
    }, {
        regid: "63",
        parid: "5",
        regname: "白银市",
    }, {
        regid: "64",
        parid: "5",
        regname: "定西市",
    }, {
        regid: "65",
        parid: "5",
        regname: "甘南市",
    }, {
        regid: "66",
        parid: "5",
        regname: "嘉峪关市",
    }, {
        regid: "67",
        parid: "5",
        regname: "金昌市",
    }, {
        regid: "68",
        parid: "5",
        regname: "酒泉市",
    }, {
        regid: "69",
        parid: "5",
        regname: "临夏市",
    }, {
        regid: "70",
        parid: "5",
        regname: "陇南市",
    }, {
        regid: "71",
        parid: "5",
        regname: "平凉市",
    }, {
        regid: "72",
        parid: "5",
        regname: "庆阳市",
    }, {
        regid: "73",
        parid: "5",
        regname: "天水市",
    }, {
        regid: "74",
        parid: "5",
        regname: "武威市",
    }, {
        regid: "75",
        parid: "5",
        regname: "张掖市",
    }, {
        regid: "76",
        parid: "6",
        regname: "广州市",
    }, {
        regid: "77",
        parid: "6",
        regname: "深圳市",
    }, {
        regid: "78",
        parid: "6",
        regname: "潮州市",
    }, {
        regid: "79",
        parid: "6",
        regname: "东莞市",
    }, {
        regid: "80",
        parid: "6",
        regname: "佛山市",
    }, {
        regid: "81",
        parid: "6",
        regname: "河源市",
    }, {
        regid: "82",
        parid: "6",
        regname: "惠州市",
    }, {
        regid: "83",
        parid: "6",
        regname: "江门市",
    }, {
        regid: "84",
        parid: "6",
        regname: "揭阳市",
    }, {
        regid: "85",
        parid: "6",
        regname: "茂名市",
    }, {
        regid: "86",
        parid: "6",
        regname: "梅州市",
    }, {
        regid: "87",
        parid: "6",
        regname: "清远市",
    }, {
        regid: "88",
        parid: "6",
        regname: "汕头市",
    }, {
        regid: "89",
        parid: "6",
        regname: "汕尾市",
    }, {
        regid: "90",
        parid: "6",
        regname: "韶关市",
    }, {
        regid: "91",
        parid: "6",
        regname: "阳江市",
    }, {
        regid: "92",
        parid: "6",
        regname: "云浮市",
    }, {
        regid: "93",
        parid: "6",
        regname: "湛江市",
    }, {
        regid: "94",
        parid: "6",
        regname: "肇庆市",
    }, {
        regid: "95",
        parid: "6",
        regname: "中山市",
    }, {
        regid: "96",
        parid: "6",
        regname: "珠海市",
    }, {
        regid: "97",
        parid: "7",
        regname: "南宁市",
    }, {
        regid: "98",
        parid: "7",
        regname: "桂林市",
    }, {
        regid: "99",
        parid: "7",
        regname: "百色市",
    }, {
        regid: "100",
        parid: "7",
        regname: "北海市",
    }, {
        regid: "101",
        parid: "7",
        regname: "崇左市",
    }, {
        regid: "102",
        parid: "7",
        regname: "防城港市",
    }, {
        regid: "103",
        parid: "7",
        regname: "贵港市",
    }, {
        regid: "104",
        parid: "7",
        regname: "河池市",
    }, {
        regid: "105",
        parid: "7",
        regname: "贺州市",
    }, {
        regid: "106",
        parid: "7",
        regname: "来宾市",
    }, {
        regid: "107",
        parid: "7",
        regname: "柳州市",
    }, {
        regid: "108",
        parid: "7",
        regname: "钦州市",
    }, {
        regid: "109",
        parid: "7",
        regname: "梧州市",
    }, {
        regid: "110",
        parid: "7",
        regname: "玉林市",
    }, {
        regid: "111",
        parid: "8",
        regname: "贵阳市",
    }, {
        regid: "112",
        parid: "8",
        regname: "安顺市",
    }, {
        regid: "113",
        parid: "8",
        regname: "毕节市",
    }, {
        regid: "114",
        parid: "8",
        regname: "六盘水市",
    }, {
        regid: "115",
        parid: "8",
        regname: "黔东南市",
    }, {
        regid: "116",
        parid: "8",
        regname: "黔南市",
    }, {
        regid: "117",
        parid: "8",
        regname: "黔西南市",
    }, {
        regid: "118",
        parid: "8",
        regname: "铜仁市",
    }, {
        regid: "119",
        parid: "8",
        regname: "遵义市",
    }, {
        regid: "120",
        parid: "9",
        regname: "海口市",
    }, {
        regid: "121",
        parid: "9",
        regname: "三亚市",
    }, {
        regid: "122",
        parid: "9",
        regname: "白沙市",
    }, {
        regid: "123",
        parid: "9",
        regname: "保亭市",
    }, {
        regid: "124",
        parid: "9",
        regname: "昌江市",
    }, {
        regid: "125",
        parid: "9",
        regname: "澄迈县市",
    }, {
        regid: "126",
        parid: "9",
        regname: "定安县市",
    }, {
        regid: "127",
        parid: "9",
        regname: "东方市",
    }, {
        regid: "128",
        parid: "9",
        regname: "乐东市",
    }, {
        regid: "129",
        parid: "9",
        regname: "临高县市",
    }, {
        regid: "130",
        parid: "9",
        regname: "陵水市",
    }, {
        regid: "131",
        parid: "9",
        regname: "琼海市",
    }, {
        regid: "132",
        parid: "9",
        regname: "琼中市",
    }, {
        regid: "133",
        parid: "9",
        regname: "屯昌县",
    }, {
        regid: "134",
        parid: "9",
        regname: "万宁市",
    }, {
        regid: "135",
        parid: "9",
        regname: "文昌市",
    }, {
        regid: "136",
        parid: "9",
        regname: "五指山市",
    }, {
        regid: "137",
        parid: "9",
        regname: "儋州市",
    }, {
        regid: "138",
        parid: "10",
        regname: "石家庄市",
    }, {
        regid: "139",
        parid: "10",
        regname: "保定市",
    }, {
        regid: "140",
        parid: "10",
        regname: "沧州市",
    }, {
        regid: "141",
        parid: "10",
        regname: "承德市",
    }, {
        regid: "142",
        parid: "10",
        regname: "邯郸市",
    }, {
        regid: "143",
        parid: "10",
        regname: "衡水市",
    }, {
        regid: "144",
        parid: "10",
        regname: "廊坊市",
    }, {
        regid: "145",
        parid: "10",
        regname: "秦皇岛市",
    }, {
        regid: "146",
        parid: "10",
        regname: "唐山市",
    }, {
        regid: "147",
        parid: "10",
        regname: "邢台市",
    }, {
        regid: "148",
        parid: "10",
        regname: "张家口市",
    }, {
        regid: "149",
        parid: "11",
        regname: "郑州市",
    }, {
        regid: "150",
        parid: "11",
        regname: "洛阳市",
    }, {
        regid: "151",
        parid: "11",
        regname: "开封市",
    }, {
        regid: "152",
        parid: "11",
        regname: "安阳市",
    }, {
        regid: "153",
        parid: "11",
        regname: "鹤壁市",
    }, {
        regid: "154",
        parid: "11",
        regname: "济源市",
    }, {
        regid: "155",
        parid: "11",
        regname: "焦作市",
    }, {
        regid: "156",
        parid: "11",
        regname: "南阳市",
    }, {
        regid: "157",
        parid: "11",
        regname: "平顶山市",
    }, {
        regid: "158",
        parid: "11",
        regname: "三门峡市",
    }, {
        regid: "159",
        parid: "11",
        regname: "商丘市",
    }, {
        regid: "160",
        parid: "11",
        regname: "新乡市",
    }, {
        regid: "161",
        parid: "11",
        regname: "信阳市",
    }, {
        regid: "162",
        parid: "11",
        regname: "许昌市",
    }, {
        regid: "163",
        parid: "11",
        regname: "周口市",
    }, {
        regid: "164",
        parid: "11",
        regname: "驻马店市",
    }, {
        regid: "165",
        parid: "11",
        regname: "漯河市",
    }, {
        regid: "166",
        parid: "11",
        regname: "濮阳市",
    }, {
        regid: "167",
        parid: "12",
        regname: "哈尔滨市",
    }, {
        regid: "168",
        parid: "12",
        regname: "大庆市",
    }, {
        regid: "169",
        parid: "12",
        regname: "大兴安岭市",
    }, {
        regid: "170",
        parid: "12",
        regname: "鹤岗市",
    }, {
        regid: "171",
        parid: "12",
        regname: "黑河市",
    }, {
        regid: "172",
        parid: "12",
        regname: "鸡西市",
    }, {
        regid: "173",
        parid: "12",
        regname: "佳木斯市",
    }, {
        regid: "174",
        parid: "12",
        regname: "牡丹江市",
    }, {
        regid: "175",
        parid: "12",
        regname: "七台河市",
    }, {
        regid: "176",
        parid: "12",
        regname: "齐齐哈尔市",
    }, {
        regid: "177",
        parid: "12",
        regname: "双鸭山市",
    }, {
        regid: "178",
        parid: "12",
        regname: "绥化市",
    }, {
        regid: "179",
        parid: "12",
        regname: "伊春市",
    }, {
        regid: "180",
        parid: "13",
        regname: "武汉市",
    }, {
        regid: "181",
        parid: "13",
        regname: "仙桃市",
    }, {
        regid: "182",
        parid: "13",
        regname: "鄂州市",
    }, {
        regid: "183",
        parid: "13",
        regname: "黄冈市",
    }, {
        regid: "184",
        parid: "13",
        regname: "黄石市",
    }, {
        regid: "185",
        parid: "13",
        regname: "荆门市",
    }, {
        regid: "186",
        parid: "13",
        regname: "荆州市",
    }, {
        regid: "187",
        parid: "13",
        regname: "潜江市",
    }, {
        regid: "188",
        parid: "13",
        regname: "神农架林区市",
    }, {
        regid: "189",
        parid: "13",
        regname: "十堰市",
    }, {
        regid: "190",
        parid: "13",
        regname: "随州市",
    }, {
        regid: "191",
        parid: "13",
        regname: "天门市",
    }, {
        regid: "192",
        parid: "13",
        regname: "咸宁市",
    }, {
        regid: "193",
        parid: "13",
        regname: "襄阳(襄樊市)",
    }, {
        regid: "194",
        parid: "13",
        regname: "孝感市",
    }, {
        regid: "195",
        parid: "13",
        regname: "宜昌市",
    }, {
        regid: "196",
        parid: "13",
        regname: "恩施市",
    }, {
        regid: "197",
        parid: "14",
        regname: "长沙市",
    }, {
        regid: "198",
        parid: "14",
        regname: "张家界市",
    }, {
        regid: "199",
        parid: "14",
        regname: "常德市",
    }, {
        regid: "200",
        parid: "14",
        regname: "郴州市",
    }, {
        regid: "201",
        parid: "14",
        regname: "衡阳市",
    }, {
        regid: "202",
        parid: "14",
        regname: "怀化市",
    }, {
        regid: "203",
        parid: "14",
        regname: "娄底市",
    }, {
        regid: "204",
        parid: "14",
        regname: "邵阳市",
    }, {
        regid: "205",
        parid: "14",
        regname: "湘潭市",
    }, {
        regid: "206",
        parid: "14",
        regname: "湘西市",
    }, {
        regid: "207",
        parid: "14",
        regname: "益阳市",
    }, {
        regid: "208",
        parid: "14",
        regname: "永州市",
    }, {
        regid: "209",
        parid: "14",
        regname: "岳阳市",
    }, {
        regid: "210",
        parid: "14",
        regname: "株洲市",
    }, {
        regid: "211",
        parid: "15",
        regname: "长春市",
    }, {
        regid: "212",
        parid: "15",
        regname: "吉林市",
    }, {
        regid: "213",
        parid: "15",
        regname: "白城市",
    }, {
        regid: "214",
        parid: "15",
        regname: "白山市",
    }, {
        regid: "215",
        parid: "15",
        regname: "辽源市",
    }, {
        regid: "216",
        parid: "15",
        regname: "四平市",
    }, {
        regid: "217",
        parid: "15",
        regname: "松原市",
    }, {
        regid: "218",
        parid: "15",
        regname: "通化市",
    }, {
        regid: "219",
        parid: "15",
        regname: "延边市",
    }, {
        regid: "220",
        parid: "16",
        regname: "南京市",
    }, {
        regid: "221",
        parid: "16",
        regname: "苏州市",
    }, {
        regid: "222",
        parid: "16",
        regname: "无锡市",
    }, {
        regid: "223",
        parid: "16",
        regname: "常州市",
    }, {
        regid: "224",
        parid: "16",
        regname: "淮安市",
    }, {
        regid: "225",
        parid: "16",
        regname: "连云港市",
    }, {
        regid: "226",
        parid: "16",
        regname: "南通市",
    }, {
        regid: "227",
        parid: "16",
        regname: "宿迁市",
    }, {
        regid: "228",
        parid: "16",
        regname: "泰州市",
    }, {
        regid: "229",
        parid: "16",
        regname: "徐州市",
    }, {
        regid: "230",
        parid: "16",
        regname: "盐城市",
    }, {
        regid: "231",
        parid: "16",
        regname: "扬州市",
    }, {
        regid: "232",
        parid: "16",
        regname: "镇江市",
    }, {
        regid: "233",
        parid: "17",
        regname: "南昌市",
    }, {
        regid: "234",
        parid: "17",
        regname: "抚州市",
    }, {
        regid: "235",
        parid: "17",
        regname: "赣州市",
    }, {
        regid: "236",
        parid: "17",
        regname: "吉安市",
    }, {
        regid: "237",
        parid: "17",
        regname: "景德镇市",
    }, {
        regid: "238",
        parid: "17",
        regname: "九江市",
    }, {
        regid: "239",
        parid: "17",
        regname: "萍乡市",
    }, {
        regid: "240",
        parid: "17",
        regname: "上饶市",
    }, {
        regid: "241",
        parid: "17",
        regname: "新余市",
    }, {
        regid: "242",
        parid: "17",
        regname: "宜春市",
    }, {
        regid: "243",
        parid: "17",
        regname: "鹰潭市",
    }, {
        regid: "244",
        parid: "18",
        regname: "沈阳市",
    }, {
        regid: "245",
        parid: "18",
        regname: "大连市",
    }, {
        regid: "246",
        parid: "18",
        regname: "鞍山市",
    }, {
        regid: "247",
        parid: "18",
        regname: "本溪市",
    }, {
        regid: "248",
        parid: "18",
        regname: "朝阳市",
    }, {
        regid: "249",
        parid: "18",
        regname: "丹东市",
    }, {
        regid: "250",
        parid: "18",
        regname: "抚顺市",
    }, {
        regid: "251",
        parid: "18",
        regname: "阜新市",
    }, {
        regid: "252",
        parid: "18",
        regname: "葫芦岛市",
    }, {
        regid: "253",
        parid: "18",
        regname: "锦州市",
    }, {
        regid: "254",
        parid: "18",
        regname: "辽阳市",
    }, {
        regid: "255",
        parid: "18",
        regname: "盘锦市",
    }, {
        regid: "256",
        parid: "18",
        regname: "铁岭市",
    }, {
        regid: "257",
        parid: "18",
        regname: "营口市",
    }, {
        regid: "258",
        parid: "19",
        regname: "呼和浩特市",
    }, {
        regid: "259",
        parid: "19",
        regname: "阿拉善盟市",
    }, {
        regid: "260",
        parid: "19",
        regname: "巴彦淖尔盟市",
    }, {
        regid: "261",
        parid: "19",
        regname: "包头市",
    }, {
        regid: "262",
        parid: "19",
        regname: "赤峰市",
    }, {
        regid: "263",
        parid: "19",
        regname: "鄂尔多斯市",
    }, {
        regid: "264",
        parid: "19",
        regname: "呼伦贝尔市",
    }, {
        regid: "265",
        parid: "19",
        regname: "通辽市",
    }, {
        regid: "266",
        parid: "19",
        regname: "乌海市",
    }, {
        regid: "267",
        parid: "19",
        regname: "乌兰察布市",
    }, {
        regid: "268",
        parid: "19",
        regname: "锡林郭勒盟市",
    }, {
        regid: "269",
        parid: "19",
        regname: "兴安盟市",
    }, {
        regid: "270",
        parid: "20",
        regname: "银川市",
    }, {
        regid: "271",
        parid: "20",
        regname: "固原市",
    }, {
        regid: "272",
        parid: "20",
        regname: "石嘴山市",
    }, {
        regid: "273",
        parid: "20",
        regname: "吴忠市",
    }, {
        regid: "274",
        parid: "20",
        regname: "中卫市",
    }, {
        regid: "275",
        parid: "21",
        regname: "西宁市",
    }, {
        regid: "276",
        parid: "21",
        regname: "果洛市",
    }, {
        regid: "277",
        parid: "21",
        regname: "海北市",
    }, {
        regid: "278",
        parid: "21",
        regname: "海东市",
    }, {
        regid: "279",
        parid: "21",
        regname: "海南市",
    }, {
        regid: "280",
        parid: "21",
        regname: "海西市",
    }, {
        regid: "281",
        parid: "21",
        regname: "黄南市",
    }, {
        regid: "282",
        parid: "21",
        regname: "玉树市",
    }, {
        regid: "283",
        parid: "22",
        regname: "济南市",
    }, {
        regid: "284",
        parid: "22",
        regname: "青岛市",
    }, {
        regid: "285",
        parid: "22",
        regname: "滨州市",
    }, {
        regid: "286",
        parid: "22",
        regname: "德州市",
    }, {
        regid: "287",
        parid: "22",
        regname: "东营市",
    }, {
        regid: "288",
        parid: "22",
        regname: "菏泽市",
    }, {
        regid: "289",
        parid: "22",
        regname: "济宁市",
    }, {
        regid: "290",
        parid: "22",
        regname: "莱芜市",
    }, {
        regid: "291",
        parid: "22",
        regname: "聊城市",
    }, {
        regid: "292",
        parid: "22",
        regname: "临沂市",
    }, {
        regid: "293",
        parid: "22",
        regname: "日照市",
    }, {
        regid: "294",
        parid: "22",
        regname: "泰安市",
    }, {
        regid: "295",
        parid: "22",
        regname: "威海市",
    }, {
        regid: "296",
        parid: "22",
        regname: "潍坊市",
    }, {
        regid: "297",
        parid: "22",
        regname: "烟台市",
    }, {
        regid: "298",
        parid: "22",
        regname: "枣庄市",
    }, {
        regid: "299",
        parid: "22",
        regname: "淄博市",
    }, {
        regid: "300",
        parid: "23",
        regname: "太原市",
    }, {
        regid: "301",
        parid: "23",
        regname: "长治市",
    }, {
        regid: "302",
        parid: "23",
        regname: "大同市",
    }, {
        regid: "303",
        parid: "23",
        regname: "晋城市",
    }, {
        regid: "304",
        parid: "23",
        regname: "晋中市",
    }, {
        regid: "305",
        parid: "23",
        regname: "临汾市",
    }, {
        regid: "306",
        parid: "23",
        regname: "吕梁市",
    }, {
        regid: "307",
        parid: "23",
        regname: "朔州市",
    }, {
        regid: "308",
        parid: "23",
        regname: "忻州市",
    }, {
        regid: "309",
        parid: "23",
        regname: "阳泉市",
    }, {
        regid: "310",
        parid: "23",
        regname: "运城市",
    }, {
        regid: "311",
        parid: "24",
        regname: "西安市",
    }, {
        regid: "312",
        parid: "24",
        regname: "安康市",
    }, {
        regid: "313",
        parid: "24",
        regname: "宝鸡市",
    }, {
        regid: "314",
        parid: "24",
        regname: "汉中市",
    }, {
        regid: "315",
        parid: "24",
        regname: "商洛市",
    }, {
        regid: "316",
        parid: "24",
        regname: "铜川市",
    }, {
        regid: "317",
        parid: "24",
        regname: "渭南市",
    }, {
        regid: "318",
        parid: "24",
        regname: "咸阳市",
    }, {
        regid: "319",
        parid: "24",
        regname: "延安市",
    }, {
        regid: "320",
        parid: "24",
        regname: "榆林市",
    }, {
        regid: "321",
        parid: "25",
        regname: "上海市",
    }, {
        regid: "322",
        parid: "26",
        regname: "成都市",
    }, {
        regid: "323",
        parid: "26",
        regname: "绵阳市",
    }, {
        regid: "324",
        parid: "26",
        regname: "阿坝市",
    }, {
        regid: "325",
        parid: "26",
        regname: "巴中市",
    }, {
        regid: "326",
        parid: "26",
        regname: "达州市",
    }, {
        regid: "327",
        parid: "26",
        regname: "德阳市",
    }, {
        regid: "328",
        parid: "26",
        regname: "甘孜市",
    }, {
        regid: "329",
        parid: "26",
        regname: "广安市",
    }, {
        regid: "330",
        parid: "26",
        regname: "广元市",
    }, {
        regid: "331",
        parid: "26",
        regname: "乐山市",
    }, {
        regid: "332",
        parid: "26",
        regname: "凉山市",
    }, {
        regid: "333",
        parid: "26",
        regname: "眉山市",
    }, {
        regid: "334",
        parid: "26",
        regname: "南充市",
    }, {
        regid: "335",
        parid: "26",
        regname: "内江市",
    }, {
        regid: "336",
        parid: "26",
        regname: "攀枝花",
    }, {
        regid: "337",
        parid: "26",
        regname: "遂宁市",
    }, {
        regid: "338",
        parid: "26",
        regname: "雅安市",
    }, {
        regid: "339",
        parid: "26",
        regname: "宜宾市",
    }, {
        regid: "340",
        parid: "26",
        regname: "资阳市",
    }, {
        regid: "341",
        parid: "26",
        regname: "自贡市",
    }, {
        regid: "342",
        parid: "26",
        regname: "泸州市",
    }, {
        regid: "343",
        parid: "27",
        regname: "天津市",
    }, {
        regid: "344",
        parid: "28",
        regname: "拉萨市",
    }, {
        regid: "345",
        parid: "28",
        regname: "阿里市",
    }, {
        regid: "346",
        parid: "28",
        regname: "昌都市",
    }, {
        regid: "347",
        parid: "28",
        regname: "林芝市",
    }, {
        regid: "348",
        parid: "28",
        regname: "那曲市",
    }, {
        regid: "349",
        parid: "28",
        regname: "日喀则市",
    }, {
        regid: "350",
        parid: "28",
        regname: "山南市",
    }, {
        regid: "351",
        parid: "29",
        regname: "乌鲁木齐市",
    }, {
        regid: "352",
        parid: "29",
        regname: "阿克苏市",
    }, {
        regid: "353",
        parid: "29",
        regname: "阿拉尔市",
    }, {
        regid: "354",
        parid: "29",
        regname: "巴音郭楞市",
    }, {
        regid: "355",
        parid: "29",
        regname: "博尔塔拉市",
    }, {
        regid: "356",
        parid: "29",
        regname: "昌吉市",
    }, {
        regid: "357",
        parid: "29",
        regname: "哈密市",
    }, {
        regid: "358",
        parid: "29",
        regname: "和田市",
    }, {
        regid: "359",
        parid: "29",
        regname: "喀什市",
    }, {
        regid: "360",
        parid: "29",
        regname: "克拉玛依市",
    }, {
        regid: "361",
        parid: "29",
        regname: "克孜勒苏市",
    }, {
        regid: "362",
        parid: "29",
        regname: "石河子",
    }, {
        regid: "363",
        parid: "29",
        regname: "图木舒克市",
    }, {
        regid: "364",
        parid: "29",
        regname: "吐鲁番市",
    }, {
        regid: "365",
        parid: "29",
        regname: "五家渠市",
    }, {
        regid: "366",
        parid: "29",
        regname: "伊犁市",
    }, {
        regid: "367",
        parid: "30",
        regname: "昆明市",
    }, {
        regid: "368",
        parid: "30",
        regname: "怒江市",
    }, {
        regid: "369",
        parid: "30",
        regname: "普洱市",
    }, {
        regid: "370",
        parid: "30",
        regname: "丽江市",
    }, {
        regid: "371",
        parid: "30",
        regname: "保山市",
    }, {
        regid: "372",
        parid: "30",
        regname: "楚雄市",
    }, {
        regid: "373",
        parid: "30",
        regname: "大理市",
    }, {
        regid: "374",
        parid: "30",
        regname: "德宏市",
    }, {
        regid: "375",
        parid: "30",
        regname: "迪庆市",
    }, {
        regid: "376",
        parid: "30",
        regname: "红河市",
    }, {
        regid: "377",
        parid: "30",
        regname: "临沧市",
    }, {
        regid: "378",
        parid: "30",
        regname: "曲靖市",
    }, {
        regid: "379",
        parid: "30",
        regname: "文山市",
    }, {
        regid: "380",
        parid: "30",
        regname: "西双版纳市",
    }, {
        regid: "381",
        parid: "30",
        regname: "玉溪市",
    }, {
        regid: "382",
        parid: "30",
        regname: "昭通市",
    }, {
        regid: "383",
        parid: "31",
        regname: "杭州市",
    }, {
        regid: "384",
        parid: "31",
        regname: "湖州市",
    }, {
        regid: "385",
        parid: "31",
        regname: "嘉兴市",
    }, {
        regid: "386",
        parid: "31",
        regname: "金华市",
    }, {
        regid: "387",
        parid: "31",
        regname: "丽水市",
    }, {
        regid: "388",
        parid: "31",
        regname: "宁波市",
    }, {
        regid: "389",
        parid: "31",
        regname: "绍兴市",
    }, {
        regid: "390",
        parid: "31",
        regname: "台州市",
    }, {
        regid: "391",
        parid: "31",
        regname: "温州市",
    }, {
        regid: "392",
        parid: "31",
        regname: "舟山市",
    }, {
        regid: "393",
        parid: "31",
        regname: "衢州市",
    }, {
        regid: "394",
        parid: "32",
        regname: "重庆市",
    }, {
        regid: "395",
        parid: "33",
        regname: "香港",
    }, {
        regid: "396",
        parid: "34",
        regname: "澳门",
    }, {
        regid: "397",
        parid: "35",
        regname: "台湾",
    } ]
};